version: '3'
services:
  bioevo:
      image: markourm/bioevo-service:tag1
      ports:
        - "8502:8502"
  report:
      image: markourm/bioevo-report-service:tag1
      ports:
        - "8501:8501"
  client:
      image: markourm/bioevo-client:tag1
      ports:
        - "8500:8500"
      depends_on:
        - bioevo
        - report